### ISSUE TITLE
Single-thread infinite loop when it failed to connect

### ISSUE THREAD

**Issue by database64128** [glitchless/MinecraftTelegramBridge#2]
The server is behind a `socks5` proxy. I started the server with this:

```
java -Xmx4G -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=11080 -Dfml.doNotBackup=true -Dfml.loginTimeout=900 -Dfml.readTimeout=90 -server -jar forge-1.12.2-14.23.5.2847-universal.jar
```

But Telegram Bridge seems to ignore the proxy setting. After timing out and throwing an exception, it started a single-thread loop.

```
[09:09:27] [Thread-10/ERROR] [telegrambridge]: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.http.HttpURLConnection.access$100(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at java.security.AccessController.doPrivileged(Native Method)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at ru.glitchless.telegrambridge.utils.HttpUtils.doPostRequest(HttpUtils.java:50)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender.sendMessageInternal(TelegramSender.java:40)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender.sendPendingMessages(TelegramSender.java:28)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at ru.glitchless.telegrambridge.telegramapi.TelegramLoop$2.run(TelegramLoop.java:14)
[09:09:27] [Thread-10/INFO] [STDERR]: [ru.glitchless.telegrambridge.telegramapi.delegate.TelegramSender:sendMessageInternal:46]: 	at ru.glitchless.telegrambridge.telegramapi.LoopWithExpRetry.run(LoopWithExpRetry.java:21)
[09:09:27] [Thread-10/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.io.EOFException: SSL peer shut down incorrectly
[09:09:27] [Thread-10/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at sun.security.ssl.InputRecord.read(Unknown Source)
[09:09:27] [Thread-10/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 19 more
```

**Comment by LionZXY** [comment]
> single-thread loop

It's okay

> ignore the proxy setting

Hm. I should add, probably

**Comment by LionZXY** [comment]
How about adding features to add proxies in the config (not command-line)?

**Comment by database64128** [comment]
> How about adding features to add proxies in the config (not command-line)?

Sorry for the delay. It's fine to add an option for proxy in the config file. But it would be better to have similar behavior with other mods, which uses the proxy passed by command line arguments.

> It's okay

An infinite loop is not okay. It uses too much server resource.

**Comment by LionZXY** [comment]
Tested: In 1.3.0 try request is exponential

**Comment by LionZXY** [comment]
@database64128 can you check proxy settings now?

**Comment by database64128** [comment]
Just checked. It still doesn't use the socks5 proxy set by passing `-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=11080`.
